### ISSUE TITLE
Check version support

### ISSUE THREAD

**Issue by ZeNyfh** [ZeNyfh/rbhop-MC#1]
since this is all just maths, there is a chance that all of this code works on older/newer versions, however this is untested.

**Comment by 9382** [comment]
General concern is the change in how hooks are managed per version, the maths should never break

**Comment by ZeNyfh** [comment]
yea, which is why I'll see/get someone to see if it can run on versions other than specifically 1.16.5

**Comment by ZeNyfh** [comment]
Yep, version support is funky, I never wish to migrate versions ever again, though that answered my question.
